apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
  labels:
    app.kubernetes.io/name: spring-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-music
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-music
    spec:
      containers:
      - image: spring-music
        name: spring-music
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
        volumeMounts:
          - name: config-volume
            mountPath: /workspace/config
            readOnly: true
          - name: db-secret-volume
            mountPath: /workspace/db-secret
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: spring-music
        - name: db-secret-volume
          secret:
            secretName: spring-music-db