---
apiVersion: v1
kind: Secret
metadata:
  name: spring-music-db
  labels:
    app.kubernetes.io/name: spring-music
type: service.binding/mysql
stringData:
  type: mysql
  host: music-mysql.mysql.svc.cluster.local
  port: "3306"
  database: music
  username: root
  password: secret

---
apiVersion: service.binding/v1alpha2
kind: ServiceBinding
metadata:
  name: spring-music-binding
  labels:
    app.kubernetes.io/name: spring-music
spec:
  application:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-music
  service:
    apiVersion: v1
    kind: Secret
    name: spring-music-db
