apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
spec:
  template:
    spec:
      containers:
        - name: spring-music
          env:
          - name: spring.profiles.active
            value: mongodb
