services:

  music-mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - music-mysql-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: music
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  spring-music:
    image: spring-music
    restart: unless-stopped
    depends_on:
      music-mysql:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - music-mysql-network
    environment:
      spring.profiles.active: mysql
      spring.datasource.url: jdbc:mysql://music-mysql:3306/music
      spring.datasource.username: test
      spring.datasource.password: test

networks:
  music-mysql-network:
