apiVersion: v1
kind: Service
metadata:
  name: spring-music
  labels:
    app.kubernetes.io/name: spring-music
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-music
  type: ClusterIP
