apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: spring-music
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: spring-music
      custom:
        buildCommand: ./gradlew bootBuildImage -x test --imageName=$IMAGE
        dependencies:
          paths:
            - src
            - build.gradle
deploy:
  kustomize:
    paths:
      - deploy/kubernetes-service-binding/base
portForward:
  - resourceType: service
    resourceName: spring-music
    namespace: default
    port: 8080
    localPort: 8080

profiles:
  - name: mongodb-server
    deploy:
      helm:
        releases:
          - name: music
            remoteChart: bitnami/mongodb
            namespace: mongodb
            createNamespace: true
            wait: true
            setValues:
              architecture: standalone
              auth.database: music
              auth.username: testuser
              auth.password: secret
  - name: mongodb
    deploy:
      kustomize:
        paths:
          - deploy/kubernetes-service-binding/overlays/mongodb
  - name: mysql-server
    deploy:
      helm:
        releases:
          - name: music-mysql
            remoteChart: bitnami/mysql
            namespace: mysql
            createNamespace: true
            wait: true
            setValues:
              architecture: standalone
              auth.database: music
              auth.username: testuser
              auth.password: secret
  - name: mysql
    deploy:
      kustomize:
        paths:
          - deploy/kubernetes-service-binding/overlays/mysql
  - name: redis-server
    deploy:
      helm:
        releases:
          - name: music-redis
            remoteChart: bitnami/redis
            namespace: redis
            createNamespace: true
            wait: true
            setValues:
              auth.password: secret
  - name: redis
    deploy:
      kustomize:
        paths:
          - deploy/kubernetes-service-binding/overlays/redis
